version: 1
cli:
  server: https://app.fossa.io
  fetcher: custom
  project: lolcode-go
analyze:
  modules:
  - name: github.com/sjansen/lolcode-go
    type: go
    target: github.com/sjansen/lolcode-go
    path: .
    options:
      all-tags: true
